### PR TITLE
allow batch as scanner option

### PR DESCRIPTION
**Pull request by yellowbrickc**
The "batch" option was documented but actually never allowed as an option.

### CODE REVIEW

**Comment by yellowbrickc** [comment]
I see that the CI is failing but maybe the pipeline is broken?
Another question: should we add the lib-folder to gitignore?
Cheers

**Comment by wdavidw** [comment]
regarding the lib folder, it shoud be committed to git

**Comment by wdavidw** [comment]
I sort of remember trying to work on it but I believed its REST implementation was buggy a few years back. Could you provide a test associated to this option. Also, I just fix the travis integration and you can use the docker command inside it `docker run --name stargate -d -p 60080:8080 sixeyed/hbase-stargate` associated with its properties `cp test/properties.docker.json test/properties.json` to easily run the tests.

**Comment by yellowbrickc** [comment]
Thanks. I'm not sure that I will succeed this weekend but I will try.

I just have a question maybe you can help: I must be able to read all cells having the same rowkey but I'm failing even if I use the option "column". I'm using a rowFilter with a GREATER op. Do you have any idea?

**Comment by yellowbrickc** [comment]
Current state of the batch option: I know that it works, because I raised it to 2000 in my current project, succesfully. On the other side I'm not able to get the test green :(
I have no idea what to do, please decide for yourself: we can either keep the code or revert it.

**Comment by wdavidw** [comment]
Sorry, I wasn't available to look at your changes. If I understood correctly, you're not suggesting to incorporate those changes submitted 2 weeks ago ?

**Comment by yellowbrickc** [comment]
sorry, I just reverted the code, I don't like red builds ;)

**Pull request closed without merging**
